[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
smartcontracts = "8naXy6dEdqVEqdfy1VXsHT2MPm1SRbjms6NZZVch676p"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
